### ISSUE TITLE
Require authentication to access datasets

### ISSUE THREAD

**Issue by kabilar** [lincbrain/linc-archive#7]
## Summary

Datasets should require authentication to access (upload and download) on front-end, CLI, and API.

## Tasks

- [x] Permissioned API tokens for CLI uploads [AK]
- [x] Test permissioned API tokens for CLI uploads [KG]
- [x] Permissioned API tokens for CLI downloads [AK]
- [x] Test permissioned API tokens for CLI downloads [KG]
- [x] Permissioned API tokens for REST API POST requests [AK]
- [x] Permissioned API tokens for REST API GET requests [AK]
- [x] Permissioned API tokens for REST API DELETE requests [AK]
- [x] Test permissioned API tokens for REST API GET requests [AK]
- [x] Permissioned API tokens for Python API uploads [AK]
- [x] Permissioned API tokens for Python API downloads [AK]
- [x] Test permissioned API tokens for Python API uploads [KG]
- [x] Test permissioned API tokens for Python API downloads [KG]
- [x] Test permissioned API tokens for Python API deletion [AK]
- [x] All approved users will have access to shared datasets.  And can embargo datasets.
